-- Phase G: Room DB 補強
-- 在 Supabase SQL Editor 執行

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS password TEXT DEFAULT NULL;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS min_level INT DEFAULT 0;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS difficulty TEXT DEFAULT 'normal';
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'public';
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS game_started BOOLEAN DEFAULT false;
ALTER TABLE room_memberships ADD COLUMN IF NOT EXISTS display_name TEXT DEFAULT 'Goblin';
ALTER TABLE room_memberships ADD COLUMN IF NOT EXISTS player_level INT DEFAULT 1;
